### ISSUE TITLE
CT build failed with status code 1

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#173]
Also in basics
```
molecule-shapes : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (molecule-shapes, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 5110ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: repo mobius missing from package.json's phetLibs for mobius/js/ThreeQuaternionIO.js
at /data/share/phet/continuous-testing/ct-snapshots/1616082139562/chipper/js/grunt/buildRunnable.js:130:5
at Array.forEach (<anonymous>:null:null)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1616082139562/chipper/js/grunt/buildRunnable.js:128:29)
at /data/share/phet/continuous-testing/ct-snapshots/1616082139562/chipper/js/grunt/Gruntfile.js:253:11
at wrap (/data/share/phet/continuous-testing/ct-snapshots/1616082139562/chipper/js/grunt/Gruntfile.js:72:7)

Full Error details:
AssertionError [ERR_ASSERTION]: repo mobius missing from package.json's phetLibs for mobius/js/ThreeQuaternionIO.js
Snapshot from 3/18/2021, 9:42:19 AM
```

**Comment by jonathanolson** [comment]
This was recently fixed, it's building now in CT. Apologies!
