### ISSUE TITLE
CT invalid x:6 e: 1

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#174]
```
molecule-shapes : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616532304876/phet-io-wrappers/state/?sim=molecule-shapes&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1616532304876%22%2C%22timestamp%22%3A1616534305944%7D
Uncaught Error: Uncaught Error: invalid x: 6, e: 1
Error: invalid x: 6, e: 1
at Function.getName (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616532304876/molecule-shapes/js/common/model/VSEPRConfiguration.js:166:15)
at new VSEPRConfiguration (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616532304876/molecule-shapes/js/common/model/VSEPRConfiguration.js:44:36)
at Function.getConfiguration (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616532304876/molecule-shapes/js/common/model/VSEPRConfiguration.js:188:29)
at VSEPRMolecule.getCentralVSEPRConfiguration (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616532304876/molecule-shapes/js/common/model/Molecule.js:186:31)
at GeometryNamePanel.getMolecularGeometryName (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616532304876/molecule-shapes/js/common/view/GeometryNamePanel.js:211:52)
at GeometryNamePanel.updateNames (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616532304876/molecule-shapes/js/common/view/GeometryNamePanel.js:199:36)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616532304876/axon/js/TinyEmitter.js:86:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616532304876/axon/js/Emitter.js:39:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616532304876/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1616532304876/axon/js/Emitter.js:64:19)
id: Bayes Chrome
Snapshot from 3/23/2021, 2:45:04 PM
```

**Comment by jonathanolson** [comment]
I've handled this specific error, but I'm stamping out others, apologies!

**Comment by KatieWoe** [comment]
Unsure what this is, but it may be related, so I'm putting it here. Also in basics sim:
```
molecule-shapes : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/phet-io-wrappers/state/?sim=molecule-shapes&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1617155925767%22%2C%22timestamp%22%3A1617170362555%7D
Uncaught Error: Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/assert/js/assert.js:25:13)
at ModelMoleculesScreenView.returnLabel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/molecule-shapes/js/common/view/MoleculeShapesScreenView.js:355:15)
at MoleculeView.removeGroup (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/molecule-shapes/js/common/view/3d/MoleculeView.js:212:27)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/axon/js/TinyEmitter.js:86:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/axon/js/Emitter.js:39:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/axon/js/Emitter.js:64:19)
at VSEPRMolecule.removeGroup (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/molecule-shapes/js/common/model/Molecule.js:354:30)
at VSEPRMolecule.removeAllGroups (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/molecule-shapes/js/common/model/Molecule.js:369:14)
at ModelMoleculesModel.reset (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/molecule-shapes/js/model/ModelMoleculesModel.js:66:33)
id: Bayes Chrome
Snapshot from 3/30/2021, 7:58:45 PM

----------------------------------

molecule-shapes : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/phet-io-wrappers/state/?sim=molecule-shapes&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1617155925767%22%2C%22timestamp%22%3A1617197340910%7D
Uncaught Error: Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/assert/js/assert.js:25:13)
at ModelMoleculesScreenView.checkOutLabel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/molecule-shapes/js/common/view/MoleculeShapesScreenView.js:346:15)
at MoleculeView.addGroup (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/molecule-shapes/js/common/view/3d/MoleculeView.js:162:149)
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/sherpa/lib/lodash-4.17.4.js:9359:14)
at new MoleculeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/molecule-shapes/js/common/view/3d/MoleculeView.js:51:7)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/molecule-shapes/js/model/ModelMoleculesScreenView.js:137:27
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/axon/js/TinyEmitter.js:86:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/axon/js/Property.js:270:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617155925767/axon/js/Property.js:185:14)
id: Bayes Chrome
Snapshot from 3/30/2021, 7:58:45 PM
```

**Comment by jonathanolson** [comment]
Ok, I believe this should FINALLY be resolved (was 4 separate subtle bugs, one of which took way too long to figure out).

@KatieWoe let me know if the above commit doesn't resolve all of the CT issues for this sim?

**Comment by KatieWoe** [comment]
Some CT issues still showing up. Are these separate @jonathanolson?
```
molecule-shapes : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/phet-io-wrappers/mirror-inputs/?sim=molecule-shapes&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1617228398632%22%2C%22timestamp%22%3A1617229892034%7D
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/assert/js/assert.js:25:13)
at MoleculeView.addGroup (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/molecule-shapes/js/common/view/3d/MoleculeView.js:187:21)
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/sherpa/lib/lodash-4.17.4.js:9359:14)
at new MoleculeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/molecule-shapes/js/common/view/3d/MoleculeView.js:58:7)
at getBondDataURL (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/molecule-shapes/js/common/view/ScreenIconNode.js:105:16)
at new ScreenIconNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/molecule-shapes/js/common/view/ScreenIconNode.js:133:17)
at new ModelMoleculesScreen (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/molecule-shapes/js/model/ModelMoleculesScreen.js:30:39)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/molecule-shapes/js/molecule-shapes-main.js:47:5
at Namespace.window.phet.joist.launchSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/joist/js/simLauncher.js:62:9)
id: Bayes Chrome
Snapshot from 3/31/2021, 4:06:38 PM

----------------------------------

molecule-shapes : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/studio/?sim=molecule-shapes&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1617228398632%22%2C%22timestamp%22%3A1617229737945%7D
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/assert/js/assert.js:25:13)
at MoleculeView.addGroup (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/molecule-shapes/js/common/view/3d/MoleculeView.js:187:21)
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/sherpa/lib/lodash-4.17.4.js:9359:14)
at new MoleculeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/molecule-shapes/js/common/view/3d/MoleculeView.js:58:7)
at getBondDataURL (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/molecule-shapes/js/common/view/ScreenIconNode.js:105:16)
at new ScreenIconNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/molecule-shapes/js/common/view/ScreenIconNode.js:133:17)
at new ModelMoleculesScreen (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/molecule-shapes/js/model/ModelMoleculesScreen.js:30:39)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/molecule-shapes/js/molecule-shapes-main.js:47:5
at Namespace.window.phet.joist.launchSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1617228398632/joist/js/simLauncher.js:62:9)
id: Bayes Chrome
Snapshot from 3/31/2021, 4:06:38 PM
```

**Comment by jonathanolson** [comment]
I solidly broke assertions for when webgl isn't enabled. Commit a minute ago should fix that! Yay for CT for catching that, hopefully should be resolved now?

**Comment by KatieWoe** [comment]
CT looks clear
