### ISSUE TITLE
CT ProjectorModeCheckbox requires sims that support the projector color profile and one other color profile

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#189]
```
molecule-shapes : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/molecule-shapes/molecule-shapes_en.html?continuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627590174278%22%2C%22timestamp%22%3A1627595775228%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: ProjectorModeCheckbox requires sims that support the projector color profile and one other color profile
Error: Assertion failed: ProjectorModeCheckbox requires sims that support the projector color profile and one other color profile
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/assert/js/assert.js:25:13)
at new ProjectorModeCheckbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/joist/js/ProjectorModeCheckbox.js:42:15)
at new GlobalOptionsNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/molecule-shapes/js/common/view/GlobalOptionsNode.js:40:22)
at createOptionsDialogContent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/molecule-shapes/js/molecule-shapes-main.js:34:41)
at new OptionsDialog (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/joist/js/OptionsDialog.js:44:21)
at PhetioCapsule.createElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/joist/js/PhetMenu.js:120:31)
at PhetioCapsule.createDynamicElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/tandem/js/PhetioDynamicElementContainer.js:230:32)
at PhetioCapsule.create (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/tandem/js/PhetioCapsule.js:106:25)
at PhetioCapsule.getElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/tandem/js/PhetioCapsule.js:69:12)
at callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/joist/js/PhetMenu.js:143:46)
id: Bayes Chrome
Snapshot from 7/29/2021, 2:22:54 PM

----------------------------------

molecule-shapes : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/molecule-shapes/molecule-shapes_en.html?continuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627590174278%22%2C%22timestamp%22%3A1627592582463%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: ProjectorModeCheckbox requires sims that support the projector color profile and one other color profile
Error: Assertion failed: ProjectorModeCheckbox requires sims that support the projector color profile and one other color profile
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/assert/js/assert.js:25:13)
at new ProjectorModeCheckbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/joist/js/ProjectorModeCheckbox.js:42:15)
at new GlobalOptionsNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/molecule-shapes/js/common/view/GlobalOptionsNode.js:40:22)
at createOptionsDialogContent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/molecule-shapes/js/molecule-shapes-main.js:34:41)
at new OptionsDialog (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/joist/js/OptionsDialog.js:44:21)
at PhetioCapsule.createElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/joist/js/PhetMenu.js:120:31)
at PhetioCapsule.createDynamicElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/tandem/js/PhetioDynamicElementContainer.js:230:32)
at PhetioCapsule.create (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/tandem/js/PhetioCapsule.js:106:25)
at PhetioCapsule.getElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/tandem/js/PhetioCapsule.js:69:12)
at callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/joist/js/PhetMenu.js:143:46)
id: Bayes Chrome
Snapshot from 7/29/2021, 2:22:54 PM

----------------------------------

molecule-shapes : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/molecule-shapes/molecule-shapes_en.html?continuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627590174278%22%2C%22timestamp%22%3A1627591656065%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.global.view.colorProfile.profileNameProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.global.view.colorProfile.profileNameProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/assert/js/assert.js:25:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/tandem/js/phetioAPIValidation.js:172:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/tandem/js/phetioAPIValidation.js:91:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/phet-io/js/phetioEngine.js:328:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/axon/js/Property.js:271:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/axon/js/Property.js:186:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/axon/js/Property.js:341:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/joist/js/Sim.js:979:57
id: Bayes Chrome
Snapshot from 7/29/2021, 2:22:54 PM

----------------------------------

molecule-shapes : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/phet-io-wrappers/mirror-inputs/?sim=molecule-shapes&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627590174278%22%2C%22timestamp%22%3A1627592546446%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.global.view.colorProfile.profileNameProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.global.view.colorProfile.profileNameProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/assert/js/assert.js:25:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/tandem/js/phetioAPIValidation.js:172:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/tandem/js/phetioAPIValidation.js:91:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/phet-io/js/phetioEngine.js:328:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/axon/js/Property.js:271:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/axon/js/Property.js:186:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/axon/js/Property.js:341:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/joist/js/Sim.js:979:57
id: Bayes Chrome
Snapshot from 7/29/2021, 2:22:54 PM

----------------------------------

molecule-shapes : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/studio/?sim=molecule-shapes&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627590174278%22%2C%22timestamp%22%3A1627592384012%7D
Uncaught Error: Uncaught Error: Assertion failed: ProjectorModeCheckbox requires sims that support the projector color profile and one other color profile
Error: Assertion failed: ProjectorModeCheckbox requires sims that support the projector color profile and one other color profile
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/assert/js/assert.js:25:13)
at new ProjectorModeCheckbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/joist/js/ProjectorModeCheckbox.js:42:15)
at new GlobalOptionsNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/molecule-shapes/js/common/view/GlobalOptionsNode.js:40:22)
at createOptionsDialogContent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/molecule-shapes/js/molecule-shapes-main.js:34:41)
at new OptionsDialog (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/joist/js/OptionsDialog.js:44:21)
at PhetioCapsule.createElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/joist/js/PhetMenu.js:120:31)
at PhetioCapsule.createArchetype (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/tandem/js/PhetioDynamicElementContainer.js:197:30)
at new PhetioDynamicElementContainer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/tandem/js/PhetioDynamicElementContainer.js:95:27)
at new PhetioCapsule (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/tandem/js/PhetioCapsule.js:42:5)
at new PhetMenu (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/joist/js/PhetMenu.js:119:30)
id: Bayes Chrome
Snapshot from 7/29/2021, 2:22:54 PM

----------------------------------

molecule-shapes : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/phet-io-wrappers/phet-io-wrappers-tests.html?sim=molecule-shapes
3 out of 4 tests passed. 1 failed.
SimTests: molecule-shapes: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.global.view.colorProfile.profileNameProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.global.view.colorProfile.profileNameProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/assert/js/assert.js:25:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/tandem/js/phetioAPIValidation.js:172:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/tandem/js/phetioAPIValidation.js:91:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/phet-io/js/phetioEngine.js:328:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/axon/js/Property.js:271:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/axon/js/Property.js:186:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/axon/js/Property.js:341:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/joist/js/Sim.js:979:57

Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.global.view.colorProfile.profileNamePropertyError: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.global.view.colorProfile.profileNameProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/assert/js/assert.js:25:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/tandem/js/phetioAPIValidation.js:172:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/tandem/js/phetioAPIValidation.js:91:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/phet-io/js/phetioEngine.js:328:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/axon/js/Property.js:271:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/axon/js/Property.js:186:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/axon/js/Property.js:341:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627590174278/joist/js/Sim.js:979:57
id: Bayes Chrome
Snapshot from 7/29/2021, 2:22:54 PM
```

**Comment by jonathanolson** [comment]
@samreid It seems like ProjectorModeCheckbox was changed. How do I have molecule-shapes-basics switch between "basics" and "projector"? The error is happening in both sims.

**Comment by samreid** [comment]
I can only see the error in molecule-shapes, and I corrected it by removing "basics" from its list of color profiles.  Ready for review.

**Comment by jonathanolson** [comment]
I had to `grunt update` for it to work (committed above). Both sims working nicely, thank you!
