### ISSUE TITLE
CT phetioID missing from the baseline that was not an archetype

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#190]
```
molecule-shapes : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/molecule-shapes/molecule-shapes_en.html?continuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627922295046%22%2C%22timestamp%22%3A1627923467825%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.global.view.colorProfile.profileNameProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.global.view.colorProfile.profileNameProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/assert/js/assert.js:25:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/tandem/js/phetioAPIValidation.js:172:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/tandem/js/phetioAPIValidation.js:91:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/phet-io/js/phetioEngine.js:328:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:271:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:186:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:341:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/joist/js/Sim.js:979:57
id: Bayes Chrome
Snapshot from 8/2/2021, 10:38:15 AM

----------------------------------

molecule-shapes : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/phet-io-wrappers/mirror-inputs/?sim=molecule-shapes&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627922295046%22%2C%22timestamp%22%3A1627923501720%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.global.view.colorProfile.profileNameProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.global.view.colorProfile.profileNameProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/assert/js/assert.js:25:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/tandem/js/phetioAPIValidation.js:172:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/tandem/js/phetioAPIValidation.js:91:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/phet-io/js/phetioEngine.js:328:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:271:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:186:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:341:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/joist/js/Sim.js:979:57
id: Bayes Chrome
Snapshot from 8/2/2021, 10:38:15 AM

----------------------------------

molecule-shapes : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/studio/?sim=molecule-shapes&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627922295046%22%2C%22timestamp%22%3A1627923333439%7D
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
moleculeShapes.global.view.colorProfile.profileNameProperty: 3. Any schema entries in the overrides file must exist in the baseline file.
Error: Assertion failed: PhET-iO API error:
moleculeShapes.global.view.colorProfile.profileNameProperty: 3. Any schema entries in the overrides file must exist in the baseline file.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/assert/js/assert.js:25:13)
at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/tandem/js/phetioAPIValidation.js:228:15)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/tandem/js/phetioAPIValidation.js:176:16)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/tandem/js/phetioAPIValidation.js:91:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/phet-io/js/phetioEngine.js:328:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:271:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:186:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:341:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/joist/js/Sim.js:979:57
id: Bayes Chrome
Snapshot from 8/2/2021, 10:38:15 AM

----------------------------------

molecule-shapes : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/phet-io-wrappers/phet-io-wrappers-tests.html?sim=molecule-shapes&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: molecule-shapes: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.global.view.colorProfile.profileNameProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.global.view.colorProfile.profileNameProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/assert/js/assert.js:25:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/tandem/js/phetioAPIValidation.js:172:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/tandem/js/phetioAPIValidation.js:91:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/phet-io/js/phetioEngine.js:328:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:271:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:186:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:341:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/joist/js/Sim.js:979:57

Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.global.view.colorProfile.profileNamePropertyError: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.global.view.colorProfile.profileNameProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/assert/js/assert.js:25:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/tandem/js/phetioAPIValidation.js:172:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/tandem/js/phetioAPIValidation.js:91:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/phet-io/js/phetioEngine.js:328:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:271:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:186:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:341:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/joist/js/Sim.js:979:57
id: Bayes Chrome
Snapshot from 8/2/2021, 10:38:15 AM

----------------------------------

molecule-shapes : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/phet-io-wrappers/phet-io-wrappers-tests.html?sim=molecule-shapes
3 out of 4 tests passed. 1 failed.
SimTests: molecule-shapes: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.global.view.colorProfile.profileNameProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.global.view.colorProfile.profileNameProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/assert/js/assert.js:25:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/tandem/js/phetioAPIValidation.js:172:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/tandem/js/phetioAPIValidation.js:91:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/phet-io/js/phetioEngine.js:328:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:271:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:186:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:341:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/joist/js/Sim.js:979:57

Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.global.view.colorProfile.profileNamePropertyError: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.global.view.colorProfile.profileNameProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/assert/js/assert.js:25:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/tandem/js/phetioAPIValidation.js:172:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/tandem/js/phetioAPIValidation.js:91:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/phet-io/js/phetioEngine.js:328:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:271:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:186:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/axon/js/Property.js:341:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627922295046/joist/js/Sim.js:979:57
id: Bayes Chrome
Snapshot from 8/2/2021, 10:38:15 AM
```

**Comment by jonathanolson** [comment]
@samreid any idea on this?

**Comment by samreid** [comment]
I updated the tandem in the overrides file, can you please review/test?

**Comment by jonathanolson** [comment]
Looks great, thanks!
