### ISSUE TITLE
CT cannot add the same listener twice

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#200]
Also in basics
```
molecule-shapes : phet-io-input-record-and-playback-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/phet-io-wrappers/input-record-and-playback/?sim=molecule-shapes&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-input-record-and-playback-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1637662989114%22%2C%22timestamp%22%3A1637674111912%7D
Uncaught Error: Uncaught Error: Assertion failed: Cannot add the same listener twice
Error: Assertion failed: Cannot add the same listener twice
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/assert/js/assert.js:25:13)
at TinyEmitter.addListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/axon/js/TinyEmitter.js:90:19)
at Emitter.addListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/axon/js/Emitter.js:73:26)
at ModelMoleculesScreenView.layout (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/molecule-shapes/js/common/view/MoleculeShapesScreenView.js:548:46)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/joist/js/Sim.js:172:46
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/sherpa/lib/lodash-4.17.4.js:9359:14)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/joist/js/Sim.js:172:15
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/axon/js/Action.js:171:22)
at Action.implementation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637662989114/chipper/dist/axon/js/Action.js:196:30)
id: Bayes Chrome
Snapshot from 11/23/2021, 3:23:09 AM
```

**Comment by jonathanolson** [comment]
It doesn't look like this is still happening. @KatieWoe have you seen this recently?
