### ISSUE TITLE
CT Any schema entries in the overrides file must be different from its baseline counterpart

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#219]
Also in Basics
```
molecule-shapes : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/molecule-shapes/molecule-shapes_en.html?continuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1660647699122%22%2C%22timestamp%22%3A1660655076565%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
moleculeShapes.modelScreen.view.bondingPanel.titleNode.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:218:14)
at assertAPIError (phetioAPIValidation.ts:187:19)
at validateOverridesFile (phetioAPIValidation.ts:87:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:277:22)
at _notifyListeners (ReadOnlyProperty.ts:228:13)
at set (Property.ts:54:10)
at (Sim.ts:929:14)
id: Bayes Puppeteer
Snapshot from 8/16/2022, 5:01:39 AM

----------------------------------

molecule-shapes : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/molecule-shapes/molecule-shapes_en.html?continuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1660647699122%22%2C%22timestamp%22%3A1660666982272%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
moleculeShapes.modelScreen.view.bondingPanel.titleNode.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:218:14)
at assertAPIError (phetioAPIValidation.ts:187:19)
at validateOverridesFile (phetioAPIValidation.ts:87:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:277:22)
at _notifyListeners (ReadOnlyProperty.ts:228:13)
at set (Property.ts:54:10)
at (Sim.ts:929:14)
id: Bayes Puppeteer
Snapshot from 8/16/2022, 5:01:39 AM

----------------------------------

molecule-shapes : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/phet-io-wrappers/state/?sim=molecule-shapes&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1660647699122%22%2C%22timestamp%22%3A1660656183107%7D
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
moleculeShapes.modelScreen.view.bondingPanel.titleNode.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:218:14)
at assertAPIError (phetioAPIValidation.ts:187:19)
at validateOverridesFile (phetioAPIValidation.ts:87:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:277:22)
at _notifyListeners (ReadOnlyProperty.ts:228:13)
at set (Property.ts:54:10)
at (Sim.ts:929:14)
id: Bayes Puppeteer
Snapshot from 8/16/2022, 5:01:39 AM

----------------------------------

molecule-shapes : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/phet-io-wrappers/phet-io-wrappers-tests.html?sim=molecule-shapes&phetioDebug=true&phetioWrapperDebug=true
32 out of 33 tests passed. 1 failed.
SimTests: molecule-shapes: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
moleculeShapes.modelScreen.view.bondingPanel.titleNode.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
moleculeShapes.modelScreen.view.bondingPanel.titleNode.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/assert/js/assert.js:28:13)
at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/chipper/dist/js/tandem/js/phetioAPIValidation.js:185:15)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/chipper/dist/js/tandem/js/phetioAPIValidation.js:157:20)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/chipper/dist/js/tandem/js/phetioAPIValidation.js:63:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/chipper/dist/js/phet-io/js/phetioEngine.js:318:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/chipper/dist/js/axon/js/ReadOnlyProperty.js:211:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/chipper/dist/js/axon/js/ReadOnlyProperty.js:161:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/chipper/dist/js/axon/js/Property.js:52:11)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/chipper/dist/js/joist/js/Sim.js:710:56

Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
moleculeShapes.modelScreen.view.bondingPanel.titleNode.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:218:14)
at assertAPIError (phetioAPIValidation.ts:187:19)
at validateOverridesFile (phetioAPIValidation.ts:87:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:277:22)
at _notifyListeners (ReadOnlyProperty.ts:228:13)
at set (Property.ts:54:10)
at (Sim.ts:929:14)
id: Bayes Puppeteer
Snapshot from 8/16/2022, 5:01:39 AM

----------------------------------

molecule-shapes : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/phet-io-wrappers/phet-io-wrappers-tests.html?sim=molecule-shapes
30 out of 31 tests passed. 1 failed.
SimTests: molecule-shapes: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
moleculeShapes.modelScreen.view.bondingPanel.titleNode.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
Error: Assertion failed: PhET-iO API error:
moleculeShapes.modelScreen.view.bondingPanel.titleNode.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/assert/js/assert.js:28:13)
at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/chipper/dist/js/tandem/js/phetioAPIValidation.js:185:15)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/chipper/dist/js/tandem/js/phetioAPIValidation.js:157:20)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/chipper/dist/js/tandem/js/phetioAPIValidation.js:63:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/chipper/dist/js/phet-io/js/phetioEngine.js:318:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/chipper/dist/js/axon/js/ReadOnlyProperty.js:211:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/chipper/dist/js/axon/js/ReadOnlyProperty.js:161:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/chipper/dist/js/axon/js/Property.js:52:11)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/chipper/dist/js/joist/js/Sim.js:710:56

Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
moleculeShapes.modelScreen.view.bondingPanel.titleNode.textProperty: 8. Any schema entries in the overrides file must be different from its baseline counterpart.Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1660647699122/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:218:14)
at assertAPIError (phetioAPIValidation.ts:187:19)
at validateOverridesFile (phetioAPIValidation.ts:87:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:277:22)
at _notifyListeners (ReadOnlyProperty.ts:228:13)
at set (Property.ts:54:10)
at (Sim.ts:929:14)
id: Bayes Puppeteer
Snapshot from 8/16/2022, 5:01:39 AM
```

**Comment by jonathanolson** [comment]
Looks like it was resolved in https://github.com/phetsims/molecule-shapes/commit/b4d1c041a9a6621953c3a80734d59f126ce9e563.
