### ISSUE TITLE
CT phetioID missing from the baseline that was not an archetype: 

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#222]
Also in Basics
```
molecule-shapes : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/molecule-shapes/molecule-shapes_en.html?continuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1662713086224%22%2C%22timestamp%22%3A1662719964156%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.modelScreen.view.bondingPanel.titleNode.visibleProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.modelScreen.view.bondingPanel.titleNode.visibleProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:163:18)
at validateOverridesFile (phetioAPIValidation.ts:85:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (Property.ts:54:10)
at (Sim.ts:902:14)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 2:44:46 AM

----------------------------------

molecule-shapes : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/molecule-shapes/molecule-shapes_en.html?continuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1662713086224%22%2C%22timestamp%22%3A1662728236788%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.modelScreen.view.bondingPanel.titleNode.visibleProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.modelScreen.view.bondingPanel.titleNode.visibleProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:163:18)
at validateOverridesFile (phetioAPIValidation.ts:85:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (Property.ts:54:10)
at (Sim.ts:902:14)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 2:44:46 AM

----------------------------------

molecule-shapes : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/phet-io-wrappers/state/?sim=molecule-shapes&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1662713086224%22%2C%22timestamp%22%3A1662720591924%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.modelScreen.view.bondingPanel.titleNode.visibleProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.modelScreen.view.bondingPanel.titleNode.visibleProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:163:18)
at validateOverridesFile (phetioAPIValidation.ts:85:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (Property.ts:54:10)
at (Sim.ts:902:14)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 2:44:46 AM

----------------------------------

molecule-shapes : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/phet-io-wrappers/state/?sim=molecule-shapes&phetioDebug=true&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1662713086224%22%2C%22timestamp%22%3A1662726395313%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.modelScreen.view.bondingPanel.titleNode.visibleProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.modelScreen.view.bondingPanel.titleNode.visibleProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:163:18)
at validateOverridesFile (phetioAPIValidation.ts:85:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (Property.ts:54:10)
at (Sim.ts:902:14)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 2:44:46 AM

----------------------------------

molecule-shapes : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/studio/?sim=molecule-shapes&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1662713086224%22%2C%22timestamp%22%3A1662720020613%7D
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
moleculeShapes.modelScreen.view.bondingPanel.titleNode.visibleProperty: 3. Any schema entries in the overrides file must exist in the baseline file.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:222:16)
at assertAPIError (phetioAPIValidation.ts:167:15)
at validateOverridesFile (phetioAPIValidation.ts:85:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (Property.ts:54:10)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 2:44:46 AM

----------------------------------

molecule-shapes : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/studio/?sim=molecule-shapes&phetioWrapperDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1662713086224%22%2C%22timestamp%22%3A1662727372377%7D
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
moleculeShapes.modelScreen.view.bondingPanel.titleNode.visibleProperty: 3. Any schema entries in the overrides file must exist in the baseline file.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:222:16)
at assertAPIError (phetioAPIValidation.ts:167:15)
at validateOverridesFile (phetioAPIValidation.ts:85:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (Property.ts:54:10)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 2:44:46 AM

----------------------------------

molecule-shapes : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/phet-io-wrappers/phet-io-wrappers-tests.html?sim=molecule-shapes&phetioDebug=true&phetioWrapperDebug=true
32 out of 33 tests passed. 1 failed.
SimTests: molecule-shapes: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.modelScreen.view.bondingPanel.titleNode.visibleProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.modelScreen.view.bondingPanel.titleNode.visibleProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/assert/js/assert.js:28:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/chipper/dist/js/tandem/js/phetioAPIValidation.js:135:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/chipper/dist/js/tandem/js/phetioAPIValidation.js:60:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/chipper/dist/js/phet-io/js/phetioEngine.js:318:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/chipper/dist/js/axon/js/ReadOnlyProperty.js:228:23)
at Property.unguardedSet (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/chipper/dist/js/axon/js/ReadOnlyProperty.js:178:14)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/chipper/dist/js/axon/js/ReadOnlyProperty.js:161:12)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/chipper/dist/js/axon/js/Property.js:52:11)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/chipper/dist/js/joist/js/Sim.js:697:56

Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.modelScreen.view.bondingPanel.titleNode.visiblePropertyError: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.modelScreen.view.bondingPanel.titleNode.visibleProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:163:18)
at validateOverridesFile (phetioAPIValidation.ts:85:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (Property.ts:54:10)
at (Sim.ts:902:14)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 2:44:46 AM

----------------------------------

molecule-shapes : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/phet-io-wrappers/phet-io-wrappers-tests.html?sim=molecule-shapes
30 out of 31 tests passed. 1 failed.
SimTests: molecule-shapes: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.modelScreen.view.bondingPanel.titleNode.visibleProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.modelScreen.view.bondingPanel.titleNode.visibleProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/assert/js/assert.js:28:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/chipper/dist/js/tandem/js/phetioAPIValidation.js:135:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/chipper/dist/js/tandem/js/phetioAPIValidation.js:60:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/chipper/dist/js/phet-io/js/phetioEngine.js:318:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/chipper/dist/js/axon/js/ReadOnlyProperty.js:228:23)
at Property.unguardedSet (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/chipper/dist/js/axon/js/ReadOnlyProperty.js:178:14)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/chipper/dist/js/axon/js/ReadOnlyProperty.js:161:12)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/chipper/dist/js/axon/js/Property.js:52:11)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/chipper/dist/js/joist/js/Sim.js:697:56

Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.modelScreen.view.bondingPanel.titleNode.visiblePropertyError: Assertion failed: phetioID missing from the baseline that was not an archetype: moleculeShapes.modelScreen.view.bondingPanel.titleNode.visibleProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1662713086224/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.ts:163:18)
at validateOverridesFile (phetioAPIValidation.ts:85:11)
at onSimStarted (phetioEngine.ts:382:28)
at listener (TinyEmitter.ts:95:8)
at emit (ReadOnlyProperty.ts:304:22)
at _notifyListeners (ReadOnlyProperty.ts:255:13)
at unguardedSet (ReadOnlyProperty.ts:239:11)
at set (Property.ts:54:10)
at (Sim.ts:902:14)
id: Bayes Puppeteer
Snapshot from 9/9/2022, 2:44:46 AM
```

**Comment by jonathanolson** [comment]
@zepumph I'm unsure how to investigate this, or what this message means. Would we be able to pair on it?

**Comment by zepumph** [comment]
It means that there was a phetioID in the overrides that was no longer in the sim (baseline). "baseline" is the sim api before the overrides are applied. 

We are talking about `phetioID missing from the baseline that was not an archetype: moleculeShapes.modelScreen.view.bondingPanel.titleNode.visibleProperty`

Here is why this occurred and why it is no longer a problem:

* First in https://github.com/phetsims/scenery/issues/1447 @samreid removed Text visibleProperties from ever being created. 
* Then in https://github.com/phetsims/molecule-shapes/commit/ca22c8c30749bfe71e4d867d1694162a568e90f2 yesterday I opted back into that visibleProperty, mostly just to get past the issue while I was working on https://github.com/phetsims/scenery/issues/1449. 

Feel free to close.

**Comment by jonathanolson** [comment]
Thanks!
