### ISSUE TITLE
CT data.initialState differs.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#253]
```
molecule-shapes : phet-io-api-compatibility : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1683641699056/molecule-shapes/molecule-shapes_en.html?continuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1683641699056%22%2C%22timestamp%22%3A1683642141984%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

moleculeShapes.realMoleculesScreen.model._data.initialState differs.
Expected:
{"bondLengthOverride":null,"bonds":[{"a":0,"b":2,"length":7,"order":0},{"a":1,"b":2,"length":7,"order":0},{"a":3,"b":2,"length":5.2635,"order":1},{"a":4,"b":2,"length":5.2635,"order":1}],"groups":[{"element":null,"isCentralAtom":false,"isLonePair":true,"position":{"x":2.6722560063508163e-15,"y":4.041451959514542,"z":5.715476013328726},"velocity":{"x":0,"y":0,"z":0}},{"element":null,"isCentralAtom":false,"isLonePair":true,"position":{"x":-1.6508564840185276e-16,"y":4.04145183921508,"z":-5.715476098393292},"velocity":{"x":0,"y":0,"z":0}},{"element":"O","isCentralAtom":true,"isLonePair":false,"position":{"x":0,"y":0,"z":0},"velocity":{"x":0,"y":0,"z":0}},{"element":"H","isCentralAtom":false,"isLonePair":false,"position":{"x":4.161794571400719,"y":-3.222405653461324,"z":0},"velocity":{"x":0,"y":0,"z":0}},{"element":"H","isCentralAtom":false,"isLonePair":false,"position":{"x":-4.161794571400719,"y":-3.222405653461324,"z":0},"velocity":{"x":0,"y":0,"z":0}}],"isReal":true,"lastMidpoint":null,"realMoleculeShape":{"displayName":"H2O"},"showRealView":true}
actual:
{"isReal":true,"groups":[{"position":{"x":2.7845344695800376e-15,"y":4.041451959514542,"z":5.715476013328726},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":-5.280718851475633e-17,"y":4.04145183921508,"z":-5.715476098393292},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":0,"y":0,"z":0},"velocity":{"x":0,"y":0,"z":0},"isLonePair":false,"element":"O","isCentralAtom":true},{"position":{"x":4.161794571400719,"y":-3.222405653461324,"z":0},"velocity":{"x":0,"y":0,"z":0},"isLonePair":false,"element":"H","isCentralAtom":false},{"position":{"x":-4.161794571400719,"y":-3.222405653461324,"z":0},"velocity":{"x":0,"y":0,"z":0},"isLonePair":false,"element":"H","isCentralAtom":false}],"bonds":[{"a":0,"b":2,"order":0,"length":7},{"a":1,"b":2,"order":0,"length":7},{"a":3,"b":2,"order":1,"length":5.2635},{"a":4,"b":2,"order":1,"length":5.2635}],"lastMidpoint":null,"realMoleculeShape":{"displayName":"H2O"},"bondLengthOverride":null,"showRealView":true}

window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1683641699056/assert/js/assert.js:28:13
at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1683641699056/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:365:22)
at addEventListener (phetioEngine.ts:352:18)
at (TinyEmitter.ts:119:18)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:266:13)
at unguardedSet (ReadOnlyProperty.ts:250:11)
at set (Property.ts:54:10)
at (Sim.ts:927:14)
at (Sim.ts:911:24)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at (Sim.ts:985:13)
at start (molecule-shapes-main.js:54:6)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
at unlockPhetioEngine (simLauncher.ts:28:6)
at then (simLauncher.ts:26:5)
id: Sparky Playwright Firefox
Snapshot from 5/9/2023, 8:14:59 AM

----------------------------------

molecule-shapes : phet-io-api-compatibility : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1683641699056/molecule-shapes/molecule-shapes_en.html?continuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1683641699056%22%2C%22timestamp%22%3A1683645509759%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

moleculeShapes.realMoleculesScreen.model._data.initialState differs.
Expected:
{"bondLengthOverride":null,"bonds":[{"a":0,"b":2,"length":7,"order":0},{"a":1,"b":2,"length":7,"order":0},{"a":3,"b":2,"length":5.2635,"order":1},{"a":4,"b":2,"length":5.2635,"order":1}],"groups":[{"element":null,"isCentralAtom":false,"isLonePair":true,"position":{"x":2.6722560063508163e-15,"y":4.041451959514542,"z":5.715476013328726},"velocity":{"x":0,"y":0,"z":0}},{"element":null,"isCentralAtom":false,"isLonePair":true,"position":{"x":-1.6508564840185276e-16,"y":4.04145183921508,"z":-5.715476098393292},"velocity":{"x":0,"y":0,"z":0}},{"element":"O","isCentralAtom":true,"isLonePair":false,"position":{"x":0,"y":0,"z":0},"velocity":{"x":0,"y":0,"z":0}},{"element":"H","isCentralAtom":false,"isLonePair":false,"position":{"x":4.161794571400719,"y":-3.222405653461324,"z":0},"velocity":{"x":0,"y":0,"z":0}},{"element":"H","isCentralAtom":false,"isLonePair":false,"position":{"x":-4.161794571400719,"y":-3.222405653461324,"z":0},"velocity":{"x":0,"y":0,"z":0}}],"isReal":true,"lastMidpoint":null,"realMoleculeShape":{"displayName":"H2O"},"showRealView":true}
actual:
{"isReal":true,"groups":[{"position":{"x":2.7845344695800376e-15,"y":4.041451959514542,"z":5.715476013328726},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":-5.280718851475633e-17,"y":4.04145183921508,"z":-5.715476098393292},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":0,"y":0,"z":0},"velocity":{"x":0,"y":0,"z":0},"isLonePair":false,"element":"O","isCentralAtom":true},{"position":{"x":4.161794571400719,"y":-3.222405653461324,"z":0},"velocity":{"x":0,"y":0,"z":0},"isLonePair":false,"element":"H","isCentralAtom":false},{"position":{"x":-4.161794571400719,"y":-3.222405653461324,"z":0},"velocity":{"x":0,"y":0,"z":0},"isLonePair":false,"element":"H","isCentralAtom":false}],"bonds":[{"a":0,"b":2,"order":0,"length":7},{"a":1,"b":2,"order":0,"length":7},{"a":3,"b":2,"order":1,"length":5.2635},{"a":4,"b":2,"order":1,"length":5.2635}],"lastMidpoint":null,"realMoleculeShape":{"displayName":"H2O"},"bondLengthOverride":null,"showRealView":true}

window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1683641699056/assert/js/assert.js:28:13
at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1683641699056/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:365:22)
at addEventListener (phetioEngine.ts:352:18)
at (TinyEmitter.ts:119:18)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:266:13)
at unguardedSet (ReadOnlyProperty.ts:250:11)
at set (Property.ts:54:10)
at (Sim.ts:927:14)
at (Sim.ts:911:24)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at (Sim.ts:985:13)
at start (molecule-shapes-main.js:54:6)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
at image (logoOnWhite_png.ts:6:0)
id: Sparky Playwright Firefox
Snapshot from 5/9/2023, 8:14:59 AM

----------------------------------

molecule-shapes : phet-io-api-compatibility : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1683641699056/molecule-shapes/molecule-shapes_en.html?continuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1683641699056%22%2C%22timestamp%22%3A1683646594787%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

moleculeShapes.realMoleculesScreen.model._data.initialState differs.
Expected:
{"bondLengthOverride":null,"bonds":[{"a":0,"b":2,"length":7,"order":0},{"a":1,"b":2,"length":7,"order":0},{"a":3,"b":2,"length":5.2635,"order":1},{"a":4,"b":2,"length":5.2635,"order":1}],"groups":[{"element":null,"isCentralAtom":false,"isLonePair":true,"position":{"x":2.6722560063508163e-15,"y":4.041451959514542,"z":5.715476013328726},"velocity":{"x":0,"y":0,"z":0}},{"element":null,"isCentralAtom":false,"isLonePair":true,"position":{"x":-1.6508564840185276e-16,"y":4.04145183921508,"z":-5.715476098393292},"velocity":{"x":0,"y":0,"z":0}},{"element":"O","isCentralAtom":true,"isLonePair":false,"position":{"x":0,"y":0,"z":0},"velocity":{"x":0,"y":0,"z":0}},{"element":"H","isCentralAtom":false,"isLonePair":false,"position":{"x":4.161794571400719,"y":-3.222405653461324,"z":0},"velocity":{"x":0,"y":0,"z":0}},{"element":"H","isCentralAtom":false,"isLonePair":false,"position":{"x":-4.161794571400719,"y":-3.222405653461324,"z":0},"velocity":{"x":0,"y":0,"z":0}}],"isReal":true,"lastMidpoint":null,"realMoleculeShape":{"displayName":"H2O"},"showRealView":true}
actual:
{"isReal":true,"groups":[{"position":{"x":2.7845344695800376e-15,"y":4.041451959514542,"z":5.715476013328726},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":-5.280718851475633e-17,"y":4.04145183921508,"z":-5.715476098393292},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":0,"y":0,"z":0},"velocity":{"x":0,"y":0,"z":0},"isLonePair":false,"element":"O","isCentralAtom":true},{"position":{"x":4.161794571400719,"y":-3.222405653461324,"z":0},"velocity":{"x":0,"y":0,"z":0},"isLonePair":false,"element":"H","isCentralAtom":false},{"position":{"x":-4.161794571400719,"y":-3.222405653461324,"z":0},"velocity":{"x":0,"y":0,"z":0},"isLonePair":false,"element":"H","isCentralAtom":false}],"bonds":[{"a":0,"b":2,"order":0,"length":7},{"a":1,"b":2,"order":0,"length":7},{"a":3,"b":2,"order":1,"length":5.2635},{"a":4,"b":2,"order":1,"length":5.2635}],"lastMidpoint":null,"realMoleculeShape":{"displayName":"H2O"},"bondLengthOverride":null,"showRealView":true}

window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1683641699056/assert/js/assert.js:28:13
at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1683641699056/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:365:22)
at addEventListener (phetioEngine.ts:352:18)
at (TinyEmitter.ts:119:18)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:266:13)
at unguardedSet (ReadOnlyProperty.ts:250:11)
at set (Property.ts:54:10)
at (Sim.ts:927:14)
at (Sim.ts:911:24)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at (Sim.ts:985:13)
at start (molecule-shapes-main.js:54:6)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
at image (logoOnWhite_png.ts:6:0)
id: Sparky Playwright Firefox
Snapshot from 5/9/2023, 8:14:59 AM

----------------------------------

molecule-shapes : phet-io-api-compatibility : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1683641699056/molecule-shapes/molecule-shapes_en.html?continuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1683641699056%22%2C%22timestamp%22%3A1683647762819%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

moleculeShapes.realMoleculesScreen.model._data.initialState differs.
Expected:
{"bondLengthOverride":null,"bonds":[{"a":0,"b":2,"length":7,"order":0},{"a":1,"b":2,"length":7,"order":0},{"a":3,"b":2,"length":5.2635,"order":1},{"a":4,"b":2,"length":5.2635,"order":1}],"groups":[{"element":null,"isCentralAtom":false,"isLonePair":true,"position":{"x":2.6722560063508163e-15,"y":4.041451959514542,"z":5.715476013328726},"velocity":{"x":0,"y":0,"z":0}},{"element":null,"isCentralAtom":false,"isLonePair":true,"position":{"x":-1.6508564840185276e-16,"y":4.04145183921508,"z":-5.715476098393292},"velocity":{"x":0,"y":0,"z":0}},{"element":"O","isCentralAtom":true,"isLonePair":false,"position":{"x":0,"y":0,"z":0},"velocity":{"x":0,"y":0,"z":0}},{"element":"H","isCentralAtom":false,"isLonePair":false,"position":{"x":4.161794571400719,"y":-3.222405653461324,"z":0},"velocity":{"x":0,"y":0,"z":0}},{"element":"H","isCentralAtom":false,"isLonePair":false,"position":{"x":-4.161794571400719,"y":-3.222405653461324,"z":0},"velocity":{"x":0,"y":0,"z":0}}],"isReal":true,"lastMidpoint":null,"realMoleculeShape":{"displayName":"H2O"},"showRealView":true}
actual:
{"isReal":true,"groups":[{"position":{"x":2.7845344695800376e-15,"y":4.041451959514542,"z":5.715476013328726},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":-5.280718851475633e-17,"y":4.04145183921508,"z":-5.715476098393292},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":0,"y":0,"z":0},"velocity":{"x":0,"y":0,"z":0},"isLonePair":false,"element":"O","isCentralAtom":true},{"position":{"x":4.161794571400719,"y":-3.222405653461324,"z":0},"velocity":{"x":0,"y":0,"z":0},"isLonePair":false,"element":"H","isCentralAtom":false},{"position":{"x":-4.161794571400719,"y":-3.222405653461324,"z":0},"velocity":{"x":0,"y":0,"z":0},"isLonePair":false,"element":"H","isCentralAtom":false}],"bonds":[{"a":0,"b":2,"order":0,"length":7},{"a":1,"b":2,"order":0,"length":7},{"a":3,"b":2,"order":1,"length":5.2635},{"a":4,"b":2,"order":1,"length":5.2635}],"lastMidpoint":null,"realMoleculeShape":{"displayName":"H2O"},"bondLengthOverride":null,"showRealView":true}

window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1683641699056/assert/js/assert.js:28:13
at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1683641699056/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:365:22)
at addEventListener (phetioEngine.ts:352:18)
at (TinyEmitter.ts:119:18)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:266:13)
at unguardedSet (ReadOnlyProperty.ts:250:11)
at set (Property.ts:54:10)
at (Sim.ts:927:14)
at (Sim.ts:911:24)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at (Sim.ts:985:13)
at start (molecule-shapes-main.js:54:6)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
at image (logoOnWhite_png.ts:6:0)
id: Sparky Playwright Firefox
Snapshot from 5/9/2023, 8:14:59 AM

----------------------------------

molecule-shapes : phet-io-api-compatibility : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1683641699056/molecule-shapes/molecule-shapes_en.html?continuousTest=%7B%22test%22%3A%5B%22molecule-shapes%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1683641699056%22%2C%22timestamp%22%3A1683648650488%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211&locales=*
Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

moleculeShapes.realMoleculesScreen.model._data.initialState differs.
Expected:
{"bondLengthOverride":null,"bonds":[{"a":0,"b":2,"length":7,"order":0},{"a":1,"b":2,"length":7,"order":0},{"a":3,"b":2,"length":5.2635,"order":1},{"a":4,"b":2,"length":5.2635,"order":1}],"groups":[{"element":null,"isCentralAtom":false,"isLonePair":true,"position":{"x":2.6722560063508163e-15,"y":4.041451959514542,"z":5.715476013328726},"velocity":{"x":0,"y":0,"z":0}},{"element":null,"isCentralAtom":false,"isLonePair":true,"position":{"x":-1.6508564840185276e-16,"y":4.04145183921508,"z":-5.715476098393292},"velocity":{"x":0,"y":0,"z":0}},{"element":"O","isCentralAtom":true,"isLonePair":false,"position":{"x":0,"y":0,"z":0},"velocity":{"x":0,"y":0,"z":0}},{"element":"H","isCentralAtom":false,"isLonePair":false,"position":{"x":4.161794571400719,"y":-3.222405653461324,"z":0},"velocity":{"x":0,"y":0,"z":0}},{"element":"H","isCentralAtom":false,"isLonePair":false,"position":{"x":-4.161794571400719,"y":-3.222405653461324,"z":0},"velocity":{"x":0,"y":0,"z":0}}],"isReal":true,"lastMidpoint":null,"realMoleculeShape":{"displayName":"H2O"},"showRealView":true}
actual:
{"isReal":true,"groups":[{"position":{"x":2.7845344695800376e-15,"y":4.041451959514542,"z":5.715476013328726},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":-5.280718851475633e-17,"y":4.04145183921508,"z":-5.715476098393292},"velocity":{"x":0,"y":0,"z":0},"isLonePair":true,"element":null,"isCentralAtom":false},{"position":{"x":0,"y":0,"z":0},"velocity":{"x":0,"y":0,"z":0},"isLonePair":false,"element":"O","isCentralAtom":true},{"position":{"x":4.161794571400719,"y":-3.222405653461324,"z":0},"velocity":{"x":0,"y":0,"z":0},"isLonePair":false,"element":"H","isCentralAtom":false},{"position":{"x":-4.161794571400719,"y":-3.222405653461324,"z":0},"velocity":{"x":0,"y":0,"z":0},"isLonePair":false,"element":"H","isCentralAtom":false}],"bonds":[{"a":0,"b":2,"order":0,"length":7},{"a":1,"b":2,"order":0,"length":7},{"a":3,"b":2,"order":1,"length":5.2635},{"a":4,"b":2,"order":1,"length":5.2635}],"lastMidpoint":null,"realMoleculeShape":{"displayName":"H2O"},"bondLengthOverride":null,"showRealView":true}

window.assertions.assertFunction<@http://127.0.0.1/continuous-testing/ct-snapshots/1683641699056/assert/js/assert.js:28:13
at window.assertions.assertFunction< (http://127.0.0.1/continuous-testing/ct-snapshots/1683641699056/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:365:22)
at addEventListener (phetioEngine.ts:352:18)
at (TinyEmitter.ts:119:18)
at emit (ReadOnlyProperty.ts:315:22)
at _notifyListeners (ReadOnlyProperty.ts:266:13)
at unguardedSet (ReadOnlyProperty.ts:250:11)
at set (Property.ts:54:10)
at (Sim.ts:927:14)
at (Sim.ts:911:24)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at i (Sim.ts:908:21)
at (Sim.ts:892:16)
at (Sim.ts:985:13)
at start (molecule-shapes-main.js:54:6)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
at image (logo_png.ts:6:0)
id: Sparky Playwright Firefox
Snapshot from 5/9/2023, 8:14:59 AM
```

**Comment by zepumph** [comment]
Solved by https://github.com/phetsims/aqua/issues/200
